-- 005_create_plan_features.sql
-- Tabla: plan_features
-- Descripción: asignaciones de features a planes con un valor dependiente del tipo de feature.
-- Columnas principales:
--   id          : uuid (PK)
--   project_id  : uuid (FK -> projects.id)
--   plan_id     : uuid (FK -> plans.id)
--   feature_id  : uuid (FK -> features.id)
--   value_json  : jsonb (valor almacenado en formato flexible; tipo validado por aplicación)
--   created_at  : timestamp
--   updated_at  : timestamp
-- Claves y restricciones:
--   PRIMARY KEY (id)
--   FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
--   FOREIGN KEY (plan_id) REFERENCES plans(id) ON DELETE CASCADE
--   FOREIGN KEY (feature_id) REFERENCES features(id) ON DELETE CASCADE
-- Índices y unicidades:
--   UNIQUE (plan_id, feature_id) -- evitar duplicados por plan
-- Notas:
--   - value puede requerir validación por tipo en la capa de aplicación (flag/numeric/value).
--   - Almacenar value como jsonb permite booleanos, numéricos o strings.
